algolia/npm-search

config.js
npm.js

This will require a full re-indexing :)

Tweak the searchableAttributes settings to consider popularName first.

---

formatPkg.js
package.json
yarn.lock

npm provides this, and in case their readme is not available (happens sometimes), we can then still get the readme from github as a fallback

feat(data): Sanitize html in readmes

---

formatPkg.js
package.json
yarn.lock

no need for custom code, and is actually technically better. See https://github.com/algolia/npm-search/pull/27#issuecomment-285950849

feat(truncate) depend on truncate-utf8-bytes

---

.babelrc
.eslintrc.js
algoliaIndex.js
config.js
formatPkg.js
index.js
log.js
npm.js
package.json
stateManager.js
yarn.lock

same setup as yarn, except no bracket spacing, since it conflicts with algolia-eslint

chore(prettier) add prettier to the toolchain

---

formatPkg.js

easier than dependents because this is only one level deep.

feat(deps) add dependencies

---

formatPkg.js

This is to be able to have a custom ranking on names with shorter length

feat(indexing) add number of words in name

---

formatPkg.js

feat(devDeps): add devDependencies

---

index.js

see https://github.com/pouchdb/pouchdb/issues/6502
Ultimately we should be able to fix this memleak by doing a serious
analysis of heap etc but last time I tried I failed at understanding
what was going on.
So for now let's try to fix "obvious" mistakes.

fix(memleak): maybe fix it

---

npm.js

This is to avoid badly formatted requests

fix(dependedUpon): encode start and end keys

---

npm.js

Made this PR via CodeSandbox 😜

Alter response for scoped packages

---

src/__tests__/npm.test.js
src/npm.js

chore: refactor npm slightly and add test

---

src/npm.js

This is one of the (fewer) bits which are tested, so if they still pass, it should work

refactor(npm): rewrite getDownloads using async/await

---

src/__tests__/__snapshots__/config.test.js.snap
src/config.js

This allows it to be filtered on!
fixes #159

feat(deprecated): add the attribute for faceting

---

src/npm.js

right now we say "something went wrong asking for the downloads of", but there's actually downloads, scoped downloads and dependents,  which are three separate things

chore(npm): cleaner error logs

---

README.md
src/__tests__/typescript.test.js
src/typescriptSupport.js

Also changed the schema to make it easier to filter based on type
cc @orta

fix(TS): support scoped packages

---

src/createAlgoliaIndex.js
src/createStateManager.js
src/formatPkg.js
src/index.js
src/jsDelivr.js
src/npm.js
src/unpkg.js

chore: rename c to config

---

src/index.js

fix(algolia): missing config param

---

src/__tests__/unpkg.test.js
src/unpkg.js

Hopefully that is what caused the errors in prod. Not sure though

fix(unpkg): remove json flag + add unit test

---

src/watch.js

I knew it was too easy.
Basically reintroduce the queue that I though a bit useless but it was not, added comment to reflect on this

process package in the right order

---

src/npm/index.js
src/watch.js

- Try to not include_docs in response, that seems to work better 
- More looog
- Forgot to await anything in the `watch()`
- `totalSequence` is shared so we don't have to query it on every loop

minifixes 2

---

src/watch.js

Not sure why it happen, logging everything so we can have more info

fix: id of null

---

.circleci/config.yml

Do nothing just setup circleci

fix: setup circleci

---

src/index.ts

fix(ts): migrate index.js

---

.circleci/config.yml
src/api.ts
src/index.ts

Add health API to be able to load the script in monitored system

feat: add health API

---

src/config.ts
src/npm/index.ts

It's not the longest query, but it's still not useful to do it at every batch.

fix: cache total downloads

---

src/utils/request.ts

Should not impact much, but because we had some issues in the Crawler with the resolver I'm trying this here too.

fix: cache dns

---

package.json

increment version manually just for the sake of it, before releasing a new image

fix: 1.0.1

---

src/watch.ts

that's what you get when you don't wait review and don't reread

fix: throw outside try

---

README.md

This PR clarifies the eligibility requirements for getting access to the index as discussed here: https://algolia.slack.com/archives/C2WQLD93Q/p1632350387498900?thread_ts=1632329402.484700&cid=C2WQLD93Q.

feat: add eligibility requirements

---

src/StateManager.ts
src/__tests__/bootstrap.test.ts
src/algolia/index.ts
src/bootstrap.ts
src/jsDelivr/index.ts

- Add some test around Bootstrap
- Report jsDelivr error to sentry

fix: report jsDelivr error and skip bootstrap

---

src/bootstrap.ts
src/formatPkg.ts
src/index.ts
src/utils/wait.ts
src/watch.ts

Throttle jobs when encountering a 429.
NPM replicate seems to be protected by Cloudflare and being too fast will throw 429 😞

fix(bootstrap): handle HTTP 429

---

.github/workflows/renovate.yml

I thought so but we didn't renamed the branch yet

fix(renovate): main -> master

---

src/config.ts

Following up on #1074 and switching the URL to our prod env.

fix(config): update jsDelivrHitsEndpoint url

---

.github/workflows/validate.yml

Renovate is excited because everything is green, but it's only because the CI didn't run :D

ci: allow to run on pull request

---

src/__tests__/api-control/npm.test.ts
src/indexers/MainBootstrapIndexer.ts
src/indexers/MainWatchIndexer.ts
src/npm/ChangesReader.ts
src/npm/Prefetcher.ts
src/npm/__tests__/index.test.ts
src/npm/index.ts
src/watch.ts

refactor: address npm replication API changes
