algolia/npm-search

- formatPkg.js
closes #22
also changes the check to add the homepage, only if it doesn't contain the repository, since the default is repo#readme, which isn't really a homepage
> feat(info) add readme and gitHead

- formatPkg.js
- package.json
- yarn.lock
We decided to save bandwidth and place in the Algolia index by storing the raw markdown instead of the rendered and escaped html. The readme isn't been run through `escape-html`, since then we can't render the markdown properly on the client
> fix(pkg.readme) don't render markdown

- config.js
- formatPkg.js
- package.json
- yarn.lock
This won't happen often at all, since for now, it should never appear. 
adds ` **TRUNCATED**` to the end of a very long README.
> feat(pkg.readme) truncate readmes longer than 450kB

- config.js
- formatPkg.js
> feat(data): add concatenated name

- formatPkg.js
this is available in the npm api, and shows the versions and when they were published.
Looks like
```json
{
"versions": {
"1.0.0": "2015-12-06T07:21:44.323Z",
"6.4.4": "2016-01-18T02:12:56.318Z",
"6.6.5": "2016-03-06T05:38:52.075Z",
"6.7.4": "2016-03-23T19:08:45.951Z",
"6.7.7": "2016-04-24T05:05:42.686Z",
"6.10.3": "2016-06-19T02:54:28.902Z",
"6.12.0": "2016-08-02T05:58:22.700Z",
"6.13.2": "2016-08-24T06:09:43.742Z",
"6.14.0": "2016-08-27T07:18:16.659Z",
"6.15.0": "2016-09-01T17:18:50.335Z",
"6.17.0": "2016-10-04T21:13:21.638Z",
"6.18.0": "2016-10-25T05:36:01.320Z",
"6.18.1": "2016-10-29T06:04:02.203Z",
"6.18.2": "2016-11-07T00:00:41.776Z",
"6.19.0": "2016-11-17T18:51:32.158Z",
"6.21.0": "2016-12-19T06:02:13.385Z",
"6.21.1-0": "2016-12-19T06:30:12.429Z",
"6.21.1": …
```
> feat(data): add "versions" attribute

- formatPkg.js
- package.json
- yarn.lock
The complexity of this function was too high according to eslint, so it wouldn't regularly let me commit. 
I broke all of the reassignments up into separate functions returning different versions.
> fix(formatPkg): rewrite get info into separate functions

- config.js
- index.js
fixes #20
In the 'watch' step, I get the state after each iteration, then if now - last time bootstrap was done is more than the time to redo the bootstrap, the settings
```js
stateManager.set({
seq: 0,
bootstrapDone: false,
});
```
are being set, which *should* make the bootstrap start over.
I am not very sure how to test this locally without having to wait a long time...
> feat(process): redo bootstrap after X amount of time

- index.js
- package.json
- yarn.lock
1. The trial expired
2. Unless we're on a pro plan, we can only see things like errors, which papertrail also did.
3. It always took very long to install, because it needed to compile native code
> chore(trace): remove @risingstack/trace

- config.js
Sorting booleans asc/desc is a bit confusing, but the opposite of popular makes sense, since you want popular first, and descending as late as possible
> feat(relevancy): add deprecated in account when sorting

- index.js
Reading up on promises and memory leaks, this might be the cause of our leak in the watch phase.
I'm not convinced that this is completely the same or that it will help, but we will see fast.
> fix(memory): don't keep a reference of the `chain` in watch

- index.js
- package.json
- yarn.lock
Promise chains are great for things that WILL resolve. If we know that
this will never resolve (like watch) then we should use a simple
callback based approach like queue/async.
This also re-ensures us that every changes are applied sequentially
(while with our previous check it was no more the case).
I hope this just works™
> fix(memleak): in watch mode, do not use promise chain

- index.js
Without this return, code will go to next change which could lead to race conditions in term of state set/get
> fix(watch): add missing return

- formatPkg.js
- github.js
This happens from time to time for no particular reason, and in that case, we need to use 'master' as a fallback
> fix(changelog): fall back to master if the gitHead is undefined

- README.md
- formatPkg.js
This is useful for when you have multiple tags (latest, beta, next, RC).
I want to show this on the Yarn website, so it needs to be in the index
> feat(tags): add `tags` to the schema

- config.js
- formatPkg.js
This is used as a custom ranking, which acts much like the `deprecated` flag, in a way that it prefers packages with `false` as the value for `badPackage`. The organisations/owners that I chose to give a lower ranking are:
- [npmtest](https://yarnpkg.com/en/packages?q=npmtest-a&p=1)
- [npmdoc](https://yarnpkg.com/en/packages?q=npmdoc-a&p=1)
These authors are just duplicating packages in a way that provides no value alltogether.
> feat(quality): add a flag for very low quality packages

- README.md
- formatPkg.js
- github.js
This is cleaner as a structure. 
It's implemented backwards-compatible, and thus won't break the frontend, it should be fairly simple to migrate to this new structure once it's reindexed, and then we can remove the `gitHead` entry here.
In fact, I did this change on the website already, I only need to open the PR of [the branch](https://github.com/algolia/yarnpkg-website/tree/fix/move-head) once it's cleared here
> feat(schema): move git head into githubRepo

- formatPkg.js
This was broken by #53 or npm not having gitHead in versions anymore.
fixes #64
Not exactly sure how I wrote that first version, but it was totally wrong, I think I copy-pasted something wrong
> fix(gitHead): put back gitHead

- config.js
This was changed when OFF became OF. As reported by @pixelastic.
I'm not really sure how this will impact the search, but I think it'll be transparent
> chore(optionalFilter): rename onlyFilter to filterOnly

- README.md
I removed githubRepo since it is not necessary anymore (and should be 'deprecated')
29f6fa0c2c4c74a630c2920dd1121478d87f65b5
> Update Schema in README

- src/__tests__/formatPkg.test.js
- src/formatPkg.js
This is useful for the babel repl which will be visible [here](https://deploy-preview-1518--babel.netlify.com/repl) + https://github.com/babel/website/pull/1518 (Yarn search change isn't visible yet, but live coded it with @xtuc)
Not all packages have a keyword, but to be installable they start with `babel-plugin-` or `@babel/plugin`
> feat(babel): add a forced keyword to babel plugins

- src/__tests__/__snapshots__/config.test.js.snap
- src/config.js
- src/index.js
- src/npm.js
> refactor(settings): put synonyms and rules in the configure file

- src/index.js
See https://pouchdb.com/api.html#changes return_docs option.
Never use return_docs: true in live mode, what we want is include_docs
> fix(watch): avoid memleak by not piling up docs

- src/__tests__/formatPkg.test.js
- src/formatPkg.js
This will be useful for the [vue-cli ui](https://github.com/vuejs/vue-cli/blob/da0d37ece4bc26c1e89d01a9b49f8f01953aa2bd/packages/%40vue/cli-ui/src/views/ProjectPluginsAdd.vue#L17).
Installable vue-cli plugins must either start with `@vue/cli-plugin` or `vue-cli-plugin` (can be scoped: `@foo/vue-cli-plugin-xxx`).
> feat(vue-cli): add a forced keyword to vue-cli plugins 

- src/index.js
We are regularly hitting the default 10s timeout when replicating.
Not exactly sure how to test that this is working more than seeing less shutdowns regarding this.
Most recent logs of a crash because of a socket timeout are:
```
Apr 02 00:55:09 npm-search app/worker.1:  { Error: ESOCKETTIMEDOUT
Apr 02 03:49:15 npm-search app/worker.1:  { Error: ESOCKETTIMEDOUT
Apr 02 07:13:01 npm-search app/worker.1:  { Error: ESOCKETTIMEDOUT
Apr 02 07:46:24 npm-search app/worker.1:  { Error: ESOCKETTIMEDOUT
Apr 02 13:00:42 npm-search app/worker.1:  { Error: ESOCKETTIMEDOUT
Apr 03 06:22:59 npm-search app/worker.1:  { Error: ESOCKETTIMEDOUT
Apr 03 08:06:23 npm-search app/worker.1:  { Error: ESOCKETTIMEDOUT
Apr 03 08:32:53 npm-search app/worker.1:  { Error: ESOCKETTIMEDOUT
Apr 03 09:54:51 npm-search …
```
> fix(timeouts): increase pouch timeout

- src/__tests__/formatPkg.test.js
- src/formatPkg.js
I made PRs to the babel and Vue implementations to use the `computedKeywords` key instead of the `keywords` key for filtering. Angular already used `computedKeywords` in the first place.
> chore(keywords): disable merging of keywords and computedKeywords

- src/__tests__/formatPkg.test.js
- src/formatPkg.js
This follows the official rules of what is considered a yeoman
package:
- name must start with `generator-`
- `yeoman-generator` must be in the keywords
When that happens, it will add `generator` to the `computedKeywords`.
> feat(yeoman): Identify yeoman generators through computedKeywords

- README.md
- src/__tests__/__snapshots__/config.test.js.snap
- src/config.js
This will give significantly more relevant results (you can try it out with the index `npm-search-relevance-test` I created to test out these settings.
I had to remove the settings to disable exact and prefix from those attributes, because it otherwise clashes with errors like
```
invalid setting for disablePrefixOnAttributes, you should requests all attributes with same priority: attr1, attr2,  does not exists
```
cc @redox, since you did the original ranking decisions here :smile:
> feat(relevance): put name, description and eywords on same level

- src/__tests__/npm.test.js
- src/npm.js
- src/saveDocs.js
npm is currently serving us 404 for it (see https://github.com/npm/registry/issues/361)
Removing this is the only solution for now. This will cut down the amount of logs we're doing, and will also make CI green again.
We can revert this commit at a later date when the issue is fixed on npm's side.
> chore(dependents): remove the data fetching

- README.md
- src/__tests__/__snapshots__/config.test.js.snap
- src/config.js
- src/index.js
- src/jsDelivr.js
- src/npm.js
- src/saveDocs.js
> feat(data): add jsDelivr hits

- README.md
- src/__tests__/__snapshots__/config.test.js.snap
- src/config.js
- src/jsDelivr.js
Adds `jsDelivrPopularity` as an additional ranking criteria after `downloadsMagnitude`. Since jsDelivr hits have lower priority than npm downloads I believe this would be OK to use even without a replica (and if the results are good we could drop the idea of a replica with separate ranking completely).
> feat(relevance): use jsDelivr hits for ranking

- src/__tests__/formatPkg.test.js
- src/formatPkg.js
Now that https://github.com/npm/rfcs/pull/19 and https://github.com/npm/cli/pull/140 have been merged (woo! yay!) a number of packages have started specifying their directory within a monorepo as a `directory` attribute on their `repository` object. See, for example, [react-dom](http://registry.npmjs.org/react-dom/16.8.2).
This PR update the `getRepositoryInfo` logic to pull path details from this directory field, if present (and fall back to trying to pull it out of the URL). If merged, it will mean the GitHub link on pages like [this one](https://yarnpkg.com/en/package/react-dom) link to the correct folder within the react monorepo (woo! yay!).
(Credit to @ybiquitous for pointing me in the right direction on this one.)
> Include directory details from repository objects

- README.md
- src/__tests__/__snapshots__/config.test.js.snap
- src/__tests__/npm.test.js
- src/__tests__/typescript.test.js
- src/config.js
- src/npm.js
- src/saveDocs.js
- src/typescriptSupport.js
- src/unpkg.js
Based [on this](https://twitter.com/mxstbr/status/1139498444777824256) discussion. This PR adds a new field to the JSON index for npm search
```sh
{
...
"types": { "ts": "included" }
}
```
or
```sh
{
...
"types": { "ts": "@types/lodash" }
}
```
and if they don't support it:
```sh
{
...
"types": {  "ts": null }
}
```
which might be absent in JSON? Or false. Actually not sure. But definitely falsy.
Running `yarn format` did a few more changes than I would have done solo, but I'll leave comments in here about what I've changed.
Note: I've not been able to successfully run this locally against a set of packages, so right now it's somewhat ready for testing but not guaranteed to be shippable without risk. Should work tho - hah. 
Adding comments now.
> Adds whether there are types for a package to an index

- src/__tests__/__snapshots__/config.test.js.snap
- src/__tests__/__snapshots__/formatPkg.test.js.snap
- src/__tests__/formatPkg.test.js
- src/__tests__/typescript.test.js
- src/config.js
- src/formatPkg.js
- src/typescriptSupport.js
This fixes multiple things (I was too lazy to make multiple PRs)
1. calculate data based on the package which doesn't end up in the index in formatPkg
2. change the npm endpoint to `registry`
cc @orta
> fix(TS): infer definitions correctly

- src/__tests__/__snapshots__/config.test.js.snap
- src/config.js
Thanks to @martinkolarik in #371
This is 4.3MB vs 70MB, so will be nice for our memory usage. Speed is 200ms vs 3200ms
> fix(jsdelivr): fetch just npm hits

- src/index.js
- src/npm/index.js
- Missing await
- Missing destruct
- Missing .js
- Added log for monitoring purpose
> fix: multiple small bugs after #379

- .eslintrc.js
- src/__tests__/changelog.test.js
- src/__tests__/config.test.js
- src/__tests__/formatPkg.test.js
- src/__tests__/typescript.test.js
Apparently the "ignorePackages" option also ignores some relative imports, where it shouldn't. The flag however works as expected.
This also would have caught the `../log` error we had earlier
> fix(lint): correct setup to require extension

- README.md
- src/__tests__/__snapshots__/formatPkg.test.js.snap
- src/__tests__/formatPkg.test.js
- src/formatPkg.js
fixes #217
1. split out getAlternativeNames
2. avoid duplicates in getAlternativeNames
3. no longer put concatenatedName in _searchInternal (not relied upon)
4. add .js or non-.js name
5. small prettier fix
6. update readme
> feat(formatPkg): add .js to alternative names

- src/index.js
- src/utils/sentry.js
- src/utils/wait.js
I didn't test this, just found it in the docs: https://docs.sentry.io/error-reporting/configuration/draining/?platform=node
> feat(sentry): wait for the right amount of time.

- src/__tests__/changelog.test.js
- src/changelog.js
Found this fun little catch in fetching info from BB. Feel free to DM me if you want a URL / package to test this on.
Second approach to this would be to somehow flag this in the `baseUrlMap` by complicating it to allow including a callback to perform additional checks, lmk what you think.
> handle bb redirect for private repo

- src/__tests__/formatPkg.test.js
- src/formatPkg.js
before we were calculating the size to truncate wrong, and packages which were too long like (decentraland-renderer, which has no readme) can still error and halt the indexing process
> fix(size): more exact truncating of readme

- package.json
- src/algolia/index.js
- src/changelog.js
- src/config.js
- src/jsDelivr/index.js
- src/npm/index.js
- src/saveDocs.js
- src/unpkg.js
- src/utils/request.js
- yarn.lock
- Upgrade some others packages (runtime this time)
- Fix got upgrade and use keep alive agent 
- Reduce bootstrap amount (100 does not even pass on my computer)
> fix(dev): upgrade env /2

- package.json
- src/@types/nice-package.ts
- src/StateManager.ts
- src/__tests__/formatPkg.test.ts
- src/config.ts
- src/formatPkg.ts
- src/index.js
- src/npm/index.ts
- src/npm/types.ts
- src/saveDocs.ts
- src/utils/sentry.ts
- src/watch.ts
- tsconfig.json
The most complexe one. 
I had to change the logic to fix the types (a good thing but introduces more changes than what I wanted).
main issues:
- Catchup was processing multiple updates in parallel but it could have an update and a delete for the same package, 
which could explain one of the issue we have with deleted packages still in the index.
- Repo provided by NicePackage was not as "clean" as we wanted, realised that while testing with real update.
- We were filtering out `deleted` packages, in `changesConsumer` (Line 127, 131) effectively never deleting packages.
> fix(ts): migrate watch.js

- package.json
- src/algolia/index.ts
- src/npm/index.ts
- src/utils/request.ts
- yarn.lock
Following @MartinKolarik answers, we were indeed lacking transparency in the user-agent.
Added in:
- All http requests
- Algoliasearch
- Nano
Took the opportunity to pool the agent for:
- algoliasearch
- nano
This should help better controlling the network throughput
> feat(requests): add user-agent and httpsAgent

- README.md
- src/bootstrap.ts
- src/config.ts
- src/jsDelivr/__test__/index.test.ts
- src/jsDelivr/index.ts
- src/saveDocs.ts
- src/watch.ts
- Catchup was wrong, changes can not be processed in batch.
I have changed the behavior during the typescript migration but now I can delete it and just leave the watch.
- Add better logging to understand what is going on
> fix: improve logging + remove catchup

- package.json
Seems like we need a repo url to allow semantic release 
https://github.com/semantic-release/semantic-release/issues/1095
> fix(package.json): add repo url

- src/__tests__/saveDocs.test.ts
- src/bootstrap.ts
- src/changelog.ts
- src/jsDelivr/index.ts
- src/npm/__tests__/index.test.ts
- src/npm/index.ts
- src/saveDocs.ts
- src/typescript/index.ts
- src/watch.ts
- Add missing methods to be able to process a single package without manipulating an array (I could just have passed an array with one package but it's less readable).
- Add "an almost integration test" for saveDocs
+ compare if it's the same batched vs one to avoid regression
> feat: add methods to process a single package

- .eslintrc
- Dockerfile
- package.json
- scripts/build.sh
- src/__tests__/saveDocs.test.ts
- src/bootstrap.ts
- src/changelog.ts
- src/config.ts
- src/index.ts
- src/jsDelivr/index.ts
- src/npm/Prefetcher.ts
- src/npm/index.ts
- src/npm/types.ts
- src/saveDocs.ts
- src/typescript/index.ts
- src/utils/log.ts
- src/utils/wait.ts
- src/watch.ts
- yarn.lock
Most batch were slowed down by the slowest package, which means fast packages were still not indexed.
Here, we take advantage of NodeJs being good with async/sync and indexing sooner.
The prefetcher, only prefetch the names of the packages, so it's not filling the memory but still provide a way to fill the queue rapidly.
In the queue we fetch package per package, which is a bit slower than fetching a pages of doc, but results in less memory used and gc sooner too.
The processing itself is the same as before, except we don't do batch but one by one (see #652) 
--- 
Except that, I have been extensively testing in Google Compute Engine, to replace slow and expensive Heroku.
I lack a deploy script, monitoring and everything else, but it's working very fine (see comments below). 
GCE being …
> feat: process package in queue instead of batch

- src/bootstrap.ts
- src/npm/Prefetcher.ts
- src/npm/index.ts
- src/watch.ts
- Slipped a processing = false
- Use `rev` to fetch package at the version we received the change for, not the future version
- Handle deleted error
> fix: mini fixes

- src/__tests__/changelog.test.ts
- src/changelog.ts
- src/config.ts
Now that we pass jsdelivr file list there is no point in loading the same data less efficiently from unpkg.
> fix: stop using unpkg for changelog

- src/bootstrap.ts
- src/config.ts
- src/watch.ts
- Increase bootstrap period because it should be less needed now and it takes too much time to reprocess that often
- Log progress to datadog to remove the need to read logs to see progress
- Log percent in 00.00% format for more precision
- Drain queue before moving index and await the copy (we missed the last few packages in the bootstrap)
> fix: various

- src/bootstrap.ts
- src/config.ts
- src/watch.ts
This should help #778 
Two retry strategy:
- Exponential backoff that blocks the queue
Useful if a service is down, skipped the job right away would just make every other fail faster.
- "Mid-term" retry.
After 3 retries, the jobs are put aside and tried later until they pass or a new update for this package comes in
> fix: naive retry strategy

- src/formatPkg.ts
Not sure in which case this happens, but we had an error `pkg.style.split` is not a function
> fix(style): resilient when not a string

- .github/workflows/renovate.yml
- .renovaterc.json
- package.json
Since we can't maintain our deps correctly, let's try with the strategy we adopted on some others repo across the org.
It creates a branch and a PR every friday, renovate will use it.
That way it can auto merge all the deps that has a valid CI, and we have only one PR to approve
> chore: add renovate weekly PR

- src/config.ts
The current URL uses an undocumented feature we'll have to remove soon due to path conflicts with some new endpoints. To avoid any disruption here, this PR switches to a new URL on our preview environment.
Once we ship all changes to the production env (and this new endpoint is added and the old one removed), I'll send another PR to switch from `data-jsdelivr-com-preview.onrender.com` to `data.jsdelivr.com`
> fix(config): update jsDelivrHitsEndpoint url

- src/typescript/index.ts
This PR solves the issue that appears to be a data problem with `npm-search` index listing yup (we've only seen a single library so far) as non-TS library.
To solve it, applies the suggestion by @jablko and reverse the logic in the `getTypeScriptSupport` function, preventing yup, or other libraries written in TypeScript from being flagged as definitely typed even if an outdated/deprecated Definitely Typed reference exists.
closes https://github.com/algolia/npm-search/issues/1089
> Fix bug that identify wrongly some TS packages as Definetely Typed 

- .github/workflows/validate.yml
I'm updating the `validate` workflow to trigger on each push, not only when a PR is created.
This is how the config on CircleCI used to work and allow to check the status of the checks before actually creating a PR (thus avoiding noise as one can debug checks without creating a PR for that)
> fix(ci): Trigger CI checks on branch push, not only on PR creation

- src/indexers/MainBootstrapIndexer.ts
- src/indexers/MainWatchIndexer.ts
- src/indexers/OneTimeBackgroundIndexer.ts
- src/indexers/PeriodicBackgroundIndexer.ts
- src/npm/Prefetcher.ts
- src/watch.ts
We use the package name as `objectID` in the helper indexes, but `objectID` is not searchable, which makes it very hard to interact with the indexes via the UI (for debugging). This adds the package name as an additional searchable attribute to all the data indexes and queues.
> fix: add package name to all records
